gui:
  colorScheme: auto
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineFgColor:
      - bold
    selectedLineBgColor: []
    inactiveViewSelectedLineBgColor: []
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
