[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
claude = "latest"
codex = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
opencode = "latest"
"github:can1357/oh-my-pi" = "latest"
uv = "latest"
node = "lts"
bun = "latest"
